"""associated email added to user column migration

Revision ID: 93829cc8f445
Revises: 
Create Date: 2017-11-18 15:03:15.977430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93829cc8f445'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###
